### PR TITLE
Vis2

### PR DESCRIPTION
**Pull request by caitlinross**
This is the branch where I've been developing various instrumentation modes.  Documentation on how to use each mode is now on the blog.  It passes all of the Travis tests, including the ones I've added to test the instrumentation.  Coverage remains at 73%.  

---

If this merge represents a feature addition to ROSS, the following items must be completed before the branch will be merged:

- [x] Document the feature on the blog (See the [Contributing guide](https://github.com/carothersc/ROSS/blob/gh-pages/CONTRIBUTING.md) in the gh-pages branch).
- [x] A TravisCI test should be created (and it should pass)
- [x] Through the test, coverage should increase

### CODE REVIEW

**Comment by gonsie** [comment]
In tw-lp.c: add the same code to `tw_lp_settype` that you did to `tw_lp_setup_types`. These functions do the same thing, but old models may still be using settype. You may also want to fix the indentation of the `if (g_st_ev_trace)` statement to make it clear that it's inside the loop.

**Comment by gonsie** [comment]
You've made same changes to the event and lp structs. Which of these variable should be carried across a checkpoint? I'll make the relevant changes to RIO.

**Comment by caitlinross** [comment]
Regarding your first comment about tw-lp.c:
I actually can't add the same thing to tw_lp_settype().  

Basically, I set up the registration of the callback functions for event tracing the same way that lp types are set up, and then there are functions that somewhat mimic tw_lp_setup_types() and tw_lp_settype() (st_evtrace_setup_types() and st_evtrace_settype(), respectively).  From what I can tell, almost no ROSS models and none of CODES uses the tw_lp_setup_types() (and thus won't use st_evtrace_setup_types()).  In the case that this does get used, it was easy to set tw_lp_setup_types() to call the st_evtrace_setup_types() function and give the model dev one less thing to worry about including. 

I think in order to do something similar with tw_lp_settype(), I'd have to add an argument to pass into the function, but I didn't want to change any of the ROSS API, so that no changes would need to be made to all models; only models that want to use the event tracing feature will need to add code.  I explain this a bit in the blog post and say that after you call tw_lp_settype(), you then need to call st_evtrace_settype().  I'm going to edit the post to make it a bit clearer and give a code example.

As for the indentation: it is showing correctly in my editor, not sure why it doesn't show up the same on Github.

Checkpoint comment:
So for tw_lp, that's trace_types, event_counters, prev_event_counters_gvt, and prev_event_counters_rt.  For tw_event, I think it's just send_lp.  I think all of these should be carried across a checkpoint.

I think the buffers would need to be checkpointed as well, right?  For each mode of instrumentation, there is a buffer that stores the collected data that will be written out at some GVT in the future.  When does RIO do checkpoints?

**Comment by gonsie** [comment]
setup_types was my attempt to simplify the ROSS API... glad to see it really filtered out to the community 😐 

I'll take a look at handling the buffers within RIO. It should be relatively easy to add the correct serialization code, even with variably sized buffers.

**Comment by caitlinross** [comment]
This branch now works fully with the CODES master branch.  All instrumentation modes can run with CODES as is, without requiring any code changes.  And of course you can run CODES models normally without instrumentation.

**Comment by caitlinross** [comment]
The current link for the post about using ROSS instrumentation is located at: [http://carothersc.github.io/ROSS/feature/instrumentation.html](http://carothersc.github.io/ROSS/feature/instrumentation.html)

I'm thinking about breaking it up a bit and organizing the info a bit better, similar to how Elsa has multiple posts on RIO.  I'm also going to add some more CODES specific details for using the instrumentation.

**Pull request merged**
