### PR TITLE
New Realtime GVT Scheduler, synch=5

### PR DESCRIPTION
**Pull request by carothersc**
Hi all;

A new ROSS "realtime" scheduler is available that computes GVT at a set realtime interval. This is for applications that have either wild rollback behaviors or a good amount of variance in the time to compute a single event.  An example PHOLD run command line is as follows:

mpirun -np 4 ./phold --synch=5 --extramem=65536 --nlp=1024 --batch=32 --gvt-interval=256 --gvt-realtime-interval=3600000 --clock-rate=3600000000 --start-events=16  --lookahead=0.10 --end=2000 > results-sync-5

Note, above you are using the new Real Time scheduler with --synch=5. Here, the --gvt-realtime-interval is the number of clock cycles between successive GVTs. So, you need to set the clock rate of
the processor you are using via --clock-rate. 

To which back to using the original ROSS optimistic schedule, just use:

mpirun -np 4 ./phold --synch=3 --extramem=65536 --nlp=1024 --batch=32 --gvt-interval=256 --gvt-realtime-interval=3600000 --clock-rate=3600000000 --start-events=16  --lookahead=0.10 --end=2000 > results-sync

Notice, they only thing that chance is the --sync option. This is because you can keep realtime
and original GVT interval settings for both command lines and the scheduler determines which set of options to us (either gvt-interval or gvt-realtime-interval). 

Enjoy!,
Chris

### CODE REVIEW

**Comment by gonsie** [comment]
CMake needs to test if the environment variable $CLOCK_SPEED is actually set...

**Comment by gonsie** [comment]
@JohnPJenkins I completely agree and I've made the changes to support that. The `--gvt-interval` command line option now sets the number of milliseconds between GVTs when used with `--synch=5`.

**Comment by laprej** [comment]
We may wish to take advantage of the [Precision Time Protocol](https://en.wikipedia.org/wiki/Precision_Time_Protocol).  From the article, "... it achieves clock accuracy in the sub-microsecond range, making it suitable for measurement and control systems."

[ptpd](https://github.com/ptpd/ptpd) contains a PTP implementation.

**Comment by gonsie** [comment]
Checklist for merging:

- [X] Tested with Travis
- [X] Coverage increases
- [X] Documentation exists: [blog post](http://carothersc.github.io/ROSS/feature/synch5.html)

**Pull request merged**
