### PR TITLE
Using custom communicator instead of MPI_COMM_WORLD

### PR DESCRIPTION
**Pull request by mdorier**
These modifications aim at replacing MPI_COMM_WORLD with an MPI_COMM_ROSS communicator (which, by default is set to MPI_COMM_WORLD in core/network-mpi.c ). Doing so allows MPI applications to use ROSS with a subset of its processes. The proposed modifications also provide a tw_comm_set function that allows users to specify a communicator to use instead of MPI_COMM_WORLD. ROSS will also check if MPI has already been initialized before calling MPI_Init. If the communicator has been replaced by a user-provided one (even if the user provided MPI_COMM_WORLD), MPI_Finalize will not be called in tw_end, and the user is expected to call it himself.

The reason for this modification is to be able to call CODES (hence ROSS) as a library inside a Swift/T workflow, that is, inside a large MPI application from which multiple instances of CODES should be able to run.

I have tested the changes in ROSS with CODES (model-net-mpi-replay with sync=1 and sync=2, on a test case using DUMPI traces on a dragonfly network), both in a context where tw_comm_set is called with a custom communicator, with MPI_COMM_WORLD, or not called at all.

---

If this merge represents a feature addition to ROSS, the following items must be completed before the branch will be merged:

- [ ] Document the feature on the blog (See the [Contributing guide](https://github.com/carothersc/ROSS/blob/gh-pages/CONTRIBUTING.md) in the gh-pages branch).
  Include a link to your blog post in the Pull Request.
- [x] One or more TravisCI tests should be created (and they should pass)
- [x] Through the TravisCI tests, coverage should increase
- [x] Test with CODES to ensure everything continues to work

### CODE REVIEW

**Comment by gonsie** [comment]
Thanks for the PR! I've never seen the MPI_Initialized call before... cool!

I would really like to exercise this addition and the possible tw_comm_set calls through our automated tests. I'm not sure the exact form that might take (perhaps we need to automate travis testing for CODES on ROSS). That said, I think this change can be merged even before those tests are in place.

**Comment by mdorier** [comment]
Since all the current tests pass, it means that not using tw_comm_set makes ROSS work properly. If you want to test tw_comm_set, you could take one test that is run in parallel and make another test that does the same thing, but starts by splitting MPI_COMM_WORLD in half, and on the first half of the processes you call tw_comm_set and then run ROSS, while the other half just call MPI_Finalize. This way if anyone uses MPI_COMM_WORLD directly in later developments of ROSS instead of MPI_COMM_ROSS, this particular test will fail.

**Comment by gonsie** [comment]
I'm pretty sure that that last commit, 6709a1c46e03df459c03c7ae8ceadbe2a5b66448, will clash with your other PR #111.

I think this feature needs a short write up on how to use it properly. Notably, tw_comm_set must be called *before* tw_init. It should include a note that developers should now be using MPI_COMM_ROSS.

**Comment by mdorier** [comment]
Ah indeed. I initially made the change to my custom_comm branch and committed it, then thought I should have actually done a new branch for that, so I re-checked out master, did another branch, modified it, and created a new pull request. I didn't know my first commit would be added to the existing pull request. I'm not sure how to deal with that, I'm not a Git expert... can you accept only the first commit of this PR (aa07576)?

**Comment by gonsie** [comment]
Okay, I removed the bad commit. I've also added some testing for this feature (and slightly reworked how ROSS creates tests). 

Do you want to write a small blog post explaining how to use this feature and why it was needed? You can email me some text as well and I can format and post it to the blog. Or I'll just write something up after merging this PR.

**Comment by mdorier** [comment]
You can use the following text:

By default, ROSS will use MPI_COMM_WORLD for all its communications. `tw_comm_set` allows the user to change the communicator used by ROSS, for instance to run ROSS on a subset of the ranks of a larger MPI application. `tw_comm_set` should be called **before** calling `tw_init`. If `tw_comm_set` is used, then the user is responsible for calling `MPI_Finalize` after calling `tw_end`.

**Note to ROSS developers:** the addition of this functionality changes the internal communicator used by ROSS. From now on, `MPI_COMM_ROSS` should be used instead of `MPI_COMM_WORLD`.

**Comment by caitlinross** [comment]
@gonsie Is it okay for this to be merged now (I can take care of it and the blog post if you want)?  I'm doing some stuff with ROSS that requires use of a sub communicator instead of MPI_COMM_WORLD so this would be useful.

**Comment by gonsie** [comment]
go for it!

**Comment by gonsie** [comment]
Thanks @caitlinross Here is a link to the blog post: http://carothersc.github.io/ROSS/ross-dev/communicators.html

**Pull request merged**
